spring:
  jackson:
    # snake case style for response json
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
# TODO: 2023/5/26  change to your database and account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/l23o6
    username: postgres
    password: lizhongxin1013

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

sa-token:
  token-style: uuid
  is-log: true
